name: Build Module

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
        pip3 install --upgrade pip
        pip3 install setuptools_rust
        python3 ./setup.py install --user
        python3 -m pip install -r tests/requirements.txt
        python3 -m unittest  tests/compatibility.py
