name: Build Module

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        curl https://sh.rustup.rs -o setup.sh
        sudo bash setup.sh --default-toolchain none -y
        sudo pip3 install --upgrade pip
        sudo pip3 install setuptools_rust
        sudo python3 ./setup.py install
        python3 -m pip install -r tests/requirements.txt
        python3 -m unittest  tests/compatibility.py
